name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
            BUILD_VERSION=$(date +%s)
            echo BUILD_VERSION : $BUILD_VERSION
            docker login --username straucorp --password dckr_pat_DfI2OokaoWFlCP21bWbskV4t9HU
            docker build . --file Dockerfile --tag firebase-distribution-github-action:$BUILD_VERSION
            docker push straucorp/firebase-distribution-github-action:$BUILD_VERSION
